# Generated by Django 3.1.6 on 2021-02-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(max_length=45)),
                ('loopbackipv4', models.CharField(max_length=35)),
                ('hostname', models.CharField(max_length=45)),
                ('macaddress', models.CharField(max_length=64)),
            ],
        ),
    ]
