# Generated by Django 3.1.3 on 2021-02-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(max_length=50)),
                ('ipv4', models.GenericIPAddressField()),
                ('macaddress', models.CharField(blank=True, max_length=30)),
                ('loopbackipv4', models.GenericIPAddressField()),
            ],
        ),
    ]
